"""empty message

Revision ID: 07b9541cf8f2
Revises: 79677c0a668b
Create Date: 2023-01-16 11:20:13.651405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b9541cf8f2'
down_revision = '79677c0a668b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('attraction_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.drop_column('address')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('rating')
        batch_op.drop_column('attraction_name')
        batch_op.drop_column('reviewer_id')

    # ### end Alembic commands ###
