"""empty message

Revision ID: 525f5a8db2c6
Revises: 07b9541cf8f2
Create Date: 2023-01-16 11:26:34.589780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525f5a8db2c6'
down_revision = '07b9541cf8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_review', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('user_review')

    # ### end Alembic commands ###
