"""empty message

Revision ID: 79677c0a668b
Revises: c02e3b15431e
Create Date: 2023-01-16 11:16:22.207153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79677c0a668b'
down_revision = 'c02e3b15431e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.drop_table('rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], name='rating_owner_id_fkey'),
    sa.PrimaryKeyConstraint('restaurant_id', name='rating_pkey')
    )
    op.drop_table('review')
    # ### end Alembic commands ###
