"""empty message

Revision ID: ee537e9f1a1a
Revises: fb8e612c6b78
Create Date: 2023-01-16 11:57:08.755364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee537e9f1a1a'
down_revision = 'fb8e612c6b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('attraction_name', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_review', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('reviewer_id')
    )
    op.drop_table('restaurants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], name='restaurants_owner_id_fkey'),
    sa.PrimaryKeyConstraint('restaurant_id', name='restaurants_pkey')
    )
    op.drop_table('review')
    # ### end Alembic commands ###
